# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

platform :ios do
  desc "build and sign ios"
  lane :sign do
    build_app(
      workspace: "ios/App/App.xcworkspace",
      configuration: "Release",
      scheme: "App",
      clean: true,
      output_directory: "ios/build",
      output_name: "App.ipa",
      skip_profile_detection: true,
      codesigning_identity: "iPhone Distribution: Plastic Patrol CIC",
      export_options: {
        method: "app-store",
        provisioningProfiles: { 
          "com.lewismakesapps.Plastic-Patrol" => "Geovation CI",
        },
        signingCertificate: "iOS Distribution",
        signingStyle: "manual",
        teamID: "29F2RH37HL"
      }
    )
  end

  desc "deploy ios to test flight"
  lane :beta do
    upload_to_testflight(
      api_key_path: "AppStoreConnectAPIKey.json",
      ipa: "ios/build/App.ipa",
      distribute_external: false,
      skip_waiting_for_build_processing: true
    )
    end
end

platform :android do
  desc "build and sign android"
  lane :sign do |options|
    build_android_app(
      task: "assemble",
      build_type: "Release",
      project_dir: 'android',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => "../../upload-keystore.jks",
        "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["KEYSTORE_ALIAS"],
        "android.injected.signing.key.password" => ENV["KEYSTORE_KEY_PASSWORD"],
      }
    )
  end

  desc "deploy android to beta"
  lane :beta do
    upload_to_play_store(
      apk: "android/app/build/outputs/apk/release/app-release.apk",
      track: "beta",
      skip_upload_metadata: true,
      skip_upload_aab: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      json_key: "GooglePlayAndroidDeveloper.json"
    )
    end
end
