platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityFirebaseCrashlytics', :path => '../../node_modules/@capacitor-community/firebase-crashlytics'
  pod 'CapacitorFirebaseAuth', :path => '../../node_modules/capacitor-firebase-auth'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
  pod 'CordovaPluginsResources', :path => '../capacitor-cordova-ios-plugins'
  # Do not delete
end

target 'App' do
  capacitor_pods
  # Add your Pods here
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'

  # https://firebase.google.com/docs/crashlytics/get-started?platform=ios&authuser=0#add-sdk
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'

end
